# Generated by Django 4.2.2 on 2024-04-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Cover_image',
            new_name='Image',
        ),
    ]
